[package]
name = "httpfromtcp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tcplistener"
path = "cmd/tcplistener/main.rs"

[[bin]]
name = "udpsender"
path = "cmd/udpsender/main.rs"

[dependencies]
